### ISSUE TITLE
self-host all external fonts

### ISSUE THREAD

**Issue by anthraxx** [anthraxx/arch-security-tracker#11]
instead of referencing external domain resources and include google fonts we should self-host those and have no foreign domain requests

**Comment by pid1** [comment]
I was trying to get some performance metrics for what Google is shipping, but it seems that the behavior varies quite a bit depending on who is accessing the site. Logged into my Google account in Chromium, and disabling the cache, I get a 20K download. When caching is enabled, [the CSS URL](https://fonts.googleapis.com/css?family=Open+Sans) sends [a truncated version](https://ptpb.pw/7fJ9). An Incognito window receives a 15.2K download, and [an extended version](https://ptpb.pw/PSjd) of the CSS file. Why this results in a smaller download, I am not entirely sure.

On-disk, the provided ttf is 213K for the Regular variant. Chromium receives the font in Google's .woff2 format. Gzip can take the on-disk size down to 110K, and woff2 takes it down to 58K.

That all to say that Google is very clearly [selecting a subset](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization#format_selection) and [serving a converted version](https://github.com/google/woff2) based on the user's browser information.

What, if any, of these actions would we like to replicate? The Apache license would cover converted subsets of the font, should we want to go that route. The Google sites have a bit of per-platform variance that we could replicate.

Considering we are not relying on any special glyphs, though, I am of the opinion that we should just fall back to the user's default and be done with it, since they'll almost assuredly have the Unicode coverage we need.

**Comment by anthraxx** [comment]
Well while all you said is right i still think its a bit of premature optimization and we can just rely on cache doing its job. TBH I don't care much about initial uncached page hit when we are just speaking about some K and i still like my bikeshed neatly shaped :yum: 
I think just supporting woff and woff2 is sufficient, it covers a wide range of stuff including android 4.4+, iOS 5.1+ and even IE9+. We will also just need regular and bold variants, no special granularity is needed. So taking into account that we only want woff and woff2 i pretty much think we can get around any per-platform dynamic switching and just have a single font-face. we can revisit optimizations if we really run into some "problems".

**Comment by pid1** [comment]
Alright. I will convert the Google-provided ttf for regular and bold to woff and woff2 and add those to app/static/font. Do we want to ship the more extensive CSS file that Google sends to Incognito users as our default? I can add what that contains to style.css.

**Comment by anthraxx** [comment]
cool, can you clarify what you mean by more extensive css file? We don't really need differentiate like Cyrillic, shouldn't a single @font-face that has both, the woff and woff2 be sufficient?

**Comment by pid1** [comment]
That should be fine for our needs, yeah. I was just referencing the [incognito version](https://ptpb.pw/PSjd) versus the logged-in [truncated version](https://ptpb.pw/7fJ9). I do not think we need that for anything, though.

**Comment by pid1** [comment]
We have [Google's upstream project](https://github.com/google/woff2) for woff2. Is there a recommended/preferred ttf to woff converter out there?

**Comment by anthraxx** [comment]
@pid1 i have no clue about existing ones. I googled a bit some time ago and found some converter... but maybe it is also just a downloader from fonts.google... no clue... guess you need to make some research or find someone with experience getting woff :yum:

**Comment by jelly** [comment]
I've used the official [woff tools](https://github.com/google/woff2) (AUR woff2-git) to decompress woff2 to ttf and then aur/ttf2woff to convert the ttf to woff format.
